/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my_package3;

import javax.swing.JFrame;

/**
 *
 * @author Julia
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_Login_Log = new javax.swing.JLabel();
        jLabel_hideScreen_Log = new javax.swing.JLabel();
        jLabel_Exit_Log = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton_Cancel_Log = new javax.swing.JButton();
        jButton_Login_Log = new javax.swing.JButton();
        jLabel_LogToRegistration_Log = new javax.swing.JLabel();
        jLabel_Username_Log = new javax.swing.JLabel();
        jLabel_Password_Log = new javax.swing.JLabel();
        jTextField_Username_Log = new javax.swing.JTextField();
        jPasswordField_Password_Log = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(228, 241, 254));

        jLabel_Login_Log.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_Login_Log.setText("Login");

        jLabel_hideScreen_Log.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_hideScreen_Log.setText("-");
        jLabel_hideScreen_Log.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_hideScreen_Log.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_hideScreen_LogMouseClicked(evt);
            }
        });

        jLabel_Exit_Log.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_Exit_Log.setText("X");
        jLabel_Exit_Log.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Exit_Log.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Exit_LogMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jLabel_Login_Log)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_hideScreen_Log)
                .addGap(30, 30, 30)
                .addComponent(jLabel_Exit_Log)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Login_Log)
                    .addComponent(jLabel_hideScreen_Log)
                    .addComponent(jLabel_Exit_Log))
                .addGap(21, 21, 21))
        );

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        jButton_Cancel_Log.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Cancel_Log.setText("cancel");
        jButton_Cancel_Log.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Cancel_Log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Cancel_LogActionPerformed(evt);
            }
        });

        jButton_Login_Log.setBackground(new java.awt.Color(51, 255, 51));
        jButton_Login_Log.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Login_Log.setText("Login");
        jButton_Login_Log.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel_LogToRegistration_Log.setText("click here to create a new account");
        jLabel_LogToRegistration_Log.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_LogToRegistration_Log.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_LogToRegistration_LogMouseClicked(evt);
            }
        });

        jLabel_Username_Log.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Username_Log.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Username_Log.setText("Username:");

        jLabel_Password_Log.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Password_Log.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Password_Log.setText("Password:");

        jTextField_Username_Log.setBackground(new java.awt.Color(153, 153, 153));
        jTextField_Username_Log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Username_LogActionPerformed(evt);
            }
        });

        jPasswordField_Password_Log.setBackground(new java.awt.Color(153, 153, 153));
        jPasswordField_Password_Log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_Password_LogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton_Cancel_Log, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(jButton_Login_Log, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Username_Log)
                            .addComponent(jLabel_Password_Log))
                        .addGap(145, 145, 145)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_Username_Log)
                            .addComponent(jPasswordField_Password_Log, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_LogToRegistration_Log)
                .addGap(120, 120, 120))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Username_Log)
                    .addComponent(jTextField_Username_Log, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Password_Log)
                    .addComponent(jPasswordField_Password_Log, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Cancel_Log)
                    .addComponent(jButton_Login_Log, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel_LogToRegistration_Log)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_Username_LogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Username_LogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Username_LogActionPerformed

    private void jPasswordField_Password_LogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_Password_LogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_Password_LogActionPerformed

    private void jButton_Cancel_LogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Cancel_LogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Cancel_LogActionPerformed

    private void jLabel_hideScreen_LogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_hideScreen_LogMouseClicked
        // TODO add your handling code here:
         this.setState(JFrame.ICONIFIED);  // minimize the Login screen
    }//GEN-LAST:event_jLabel_hideScreen_LogMouseClicked

    private void jLabel_Exit_LogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Exit_LogMouseClicked
        // TODO add your handling code here:
        System.exit(0); //close the Login window
    }//GEN-LAST:event_jLabel_Exit_LogMouseClicked

    private void jLabel_LogToRegistration_LogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_LogToRegistration_LogMouseClicked
        Registration rg = new Registration();
        rg.setVisible(true);
        rg.pack();
        rg.setLocationRelativeTo(null);
        rg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        
        
    }//GEN-LAST:event_jLabel_LogToRegistration_LogMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cancel_Log;
    private javax.swing.JButton jButton_Login_Log;
    private javax.swing.JLabel jLabel_Exit_Log;
    private javax.swing.JLabel jLabel_LogToRegistration_Log;
    private javax.swing.JLabel jLabel_Login_Log;
    private javax.swing.JLabel jLabel_Password_Log;
    private javax.swing.JLabel jLabel_Username_Log;
    private javax.swing.JLabel jLabel_hideScreen_Log;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField_Password_Log;
    private javax.swing.JTextField jTextField_Username_Log;
    // End of variables declaration//GEN-END:variables
}
