package GUI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author patricia
 */
public class addAppointment extends javax.swing.JFrame {

    /**
     * Creates new form addAppointment
     */
    public addAppointment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newAppointment = new javax.swing.JPanel();
        eventname = new javax.swing.JLabel();
        eventdate = new javax.swing.JLabel();
        eventsduration = new javax.swing.JLabel();
        eventlocation = new javax.swing.JLabel();
        eventparticipants = new javax.swing.JLabel();
        eventpriority = new javax.swing.JLabel();
        add_button = new javax.swing.JButton();
        exit_button = new javax.swing.JButton();
        event_name = new javax.swing.JTextField();
        event_duration = new javax.swing.JTextField();
        event_location = new javax.swing.JTextField();
        priority_box = new javax.swing.JComboBox<>();
        eventreminder = new javax.swing.JLabel();
        reminder_box = new javax.swing.JComboBox<>();
        event_participants = new javax.swing.JTextField();
        event_date = new javax.swing.JFormattedTextField();
        newappointment = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        newAppointment.setBackground(new java.awt.Color(137, 196, 244));
        newAppointment.setAutoscrolls(true);

        eventname.setText("Name of event ");

        eventdate.setText("Date of event");

        eventsduration.setText("Duration of event");

        eventlocation.setText("Location of event");

        eventparticipants.setText("Participants");

        eventpriority.setText("Priority");

        add_button.setText("Add");
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });

        exit_button.setText("exit");

        event_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                event_nameActionPerformed(evt);
            }
        });

        event_duration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                event_durationActionPerformed(evt);
            }
        });

        priority_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "low", "medium", "high" }));
        priority_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priority_boxActionPerformed(evt);
            }
        });

        eventreminder.setText("Reminder");

        reminder_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 week", "3 days", "1 hour", "10 minutes" }));

        event_participants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                event_participantsActionPerformed(evt);
            }
        });

        event_date.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        newappointment.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        newappointment.setText("new Appointment");

        javax.swing.GroupLayout newAppointmentLayout = new javax.swing.GroupLayout(newAppointment);
        newAppointment.setLayout(newAppointmentLayout);
        newAppointmentLayout.setHorizontalGroup(
            newAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newAppointmentLayout.createSequentialGroup()
                .addGroup(newAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newAppointmentLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(newAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eventname)
                            .addComponent(eventdate)
                            .addComponent(eventparticipants)
                            .addComponent(eventlocation)
                            .addComponent(eventsduration)
                            .addComponent(eventreminder)
                            .addComponent(eventpriority)
                            .addComponent(newappointment)))
                    .addGroup(newAppointmentLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(exit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(newAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newAppointmentLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(newAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(newAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(event_name, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                    .addComponent(event_duration)
                                    .addComponent(event_location)
                                    .addComponent(event_participants)
                                    .addComponent(event_date))
                                .addComponent(priority_box, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(reminder_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addGroup(newAppointmentLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        newAppointmentLayout.setVerticalGroup(
            newAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newAppointmentLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(newappointment)
                .addGap(32, 32, 32)
                .addGroup(newAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newAppointmentLayout.createSequentialGroup()
                        .addGroup(newAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(newAppointmentLayout.createSequentialGroup()
                                .addGroup(newAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(eventname)
                                    .addComponent(event_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(eventdate)
                                .addGap(18, 18, 18)
                                .addComponent(eventsduration))
                            .addGroup(newAppointmentLayout.createSequentialGroup()
                                .addComponent(event_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(event_duration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(eventlocation))
                    .addComponent(event_location, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eventparticipants)
                    .addComponent(event_participants, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eventpriority)
                    .addComponent(priority_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(eventreminder)
                    .addComponent(reminder_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(newAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exit_button)
                    .addComponent(add_button))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newAppointment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newAppointment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_buttonActionPerformed

    private void priority_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priority_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priority_boxActionPerformed

    private void event_durationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_event_durationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_event_durationActionPerformed

    private void event_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_event_nameActionPerformed

    private void event_participantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_event_participantsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_event_participantsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addAppointment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_button;
    private javax.swing.JFormattedTextField event_date;
    private javax.swing.JTextField event_duration;
    private javax.swing.JTextField event_location;
    private javax.swing.JTextField event_name;
    private javax.swing.JTextField event_participants;
    private javax.swing.JLabel eventdate;
    private javax.swing.JLabel eventlocation;
    private javax.swing.JLabel eventname;
    private javax.swing.JLabel eventparticipants;
    private javax.swing.JLabel eventpriority;
    private javax.swing.JLabel eventreminder;
    private javax.swing.JLabel eventsduration;
    private javax.swing.JButton exit_button;
    private javax.swing.JPanel newAppointment;
    private javax.swing.JLabel newappointment;
    private javax.swing.JComboBox<String> priority_box;
    private javax.swing.JComboBox<String> reminder_box;
    // End of variables declaration//GEN-END:variables
}
